### ISSUE TITLE
Blank screen after full index synchronization in PWA

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#983]
After downloading the entire index (in several partitions) in the PWA on iPhone X the screen went blank and it was necessary to restart the app, upon which only the most recent index partition was available.

**Comment by castaway** [comment]
Could be related to / fixed with the #713 fix, will need to test it and see

**Comment by piratefinn** [comment]
@gtandersen As the above mentioned issue has been closed, I will assume it was deployed. Does the issue still occur?

**Comment by gtandersen** [comment]
Tried to reproduce this now and could not; closing issue.
